// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/reservation.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_PENDENTE_CONFIRMACAO           ReservationStatus = 1
	ReservationStatus_CONFIRMADA                     ReservationStatus = 2
	ReservationStatus_CANCELADA                      ReservationStatus = 3
	ReservationStatus_EXPIRADA                       ReservationStatus = 4
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "PENDENTE_CONFIRMACAO",
		2: "CONFIRMADA",
		3: "CANCELADA",
		4: "EXPIRADA",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"PENDENTE_CONFIRMACAO":           1,
		"CONFIRMADA":                     2,
		"CANCELADA":                      3,
		"EXPIRADA":                       4,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reservation_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_proto_reservation_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{0}
}

type TimeSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "HH:MM" (ex: "09:00", "09:30")
	StartTime     string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_proto_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                            // "YYYY-MM-DD"
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "HH:MM"
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "HH:MM"
	Status        ReservationStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=booking.v1.ReservationStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 em string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_proto_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Reservation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Reservation) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Reservation) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Reservation) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *Reservation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 1. ListAvailable
type ListAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // "YYYY-MM-DD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableRequest) Reset() {
	*x = ListAvailableRequest{}
	mi := &file_proto_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableRequest) ProtoMessage() {}

func (x *ListAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *ListAvailableRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type RoomAvailability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FreeSlots     []*TimeSlot            `protobuf:"bytes,2,rep,name=free_slots,json=freeSlots,proto3" json:"free_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomAvailability) Reset() {
	*x = RoomAvailability{}
	mi := &file_proto_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAvailability) ProtoMessage() {}

func (x *RoomAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAvailability.ProtoReflect.Descriptor instead.
func (*RoomAvailability) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *RoomAvailability) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomAvailability) GetFreeSlots() []*TimeSlot {
	if x != nil {
		return x.FreeSlots
	}
	return nil
}

type ListAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomAvailability    `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableResponse) Reset() {
	*x = ListAvailableResponse{}
	mi := &file_proto_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableResponse) ProtoMessage() {}

func (x *ListAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *ListAvailableResponse) GetRooms() []*RoomAvailability {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 2. CreateReservation
type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                            // "YYYY-MM-DD"
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "HH:MM"
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "HH:MM"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_proto_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReservationRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateReservationRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateReservationRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateReservationRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=booking.v1.ReservationStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_proto_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CreateReservationResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *CreateReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 3. CancelReservation
type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_proto_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReservationStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=booking.v1.ReservationStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_proto_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *CancelReservationResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *CancelReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 4. ConfirmReservation
type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_proto_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ConfirmReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReservationStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=booking.v1.ReservationStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_proto_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmReservationResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *ConfirmReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_reservation_proto protoreflect.FileDescriptor

const file_proto_reservation_proto_rawDesc = "" +
	"\n" +
	"\x17proto/reservation.proto\x12\n" +
	"booking.v1\"D\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\"\xda\x01\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x125\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1d.booking.v1.ReservationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"*\n" +
	"\x14ListAvailableRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"`\n" +
	"\x10RoomAvailability\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x123\n" +
	"\n" +
	"free_slots\x18\x02 \x03(\v2\x14.booking.v1.TimeSlotR\tfreeSlots\"K\n" +
	"\x15ListAvailableResponse\x122\n" +
	"\x05rooms\x18\x01 \x03(\v2\x1c.booking.v1.RoomAvailabilityR\x05rooms\"\x81\x01\n" +
	"\x18CreateReservationRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\"\x93\x01\n" +
	"\x19CreateReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.booking.v1.ReservationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"l\n" +
	"\x19CancelReservationResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.booking.v1.ReservationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x19ConfirmReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"m\n" +
	"\x1aConfirmReservationResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.booking.v1.ReservationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*~\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PENDENTE_CONFIRMACAO\x10\x01\x12\x0e\n" +
	"\n" +
	"CONFIRMADA\x10\x02\x12\r\n" +
	"\tCANCELADA\x10\x03\x12\f\n" +
	"\bEXPIRADA\x10\x042\x93\x03\n" +
	"\x12ReservationService\x12T\n" +
	"\rListAvailable\x12 .booking.v1.ListAvailableRequest\x1a!.booking.v1.ListAvailableResponse\x12`\n" +
	"\x11CreateReservation\x12$.booking.v1.CreateReservationRequest\x1a%.booking.v1.CreateReservationResponse\x12`\n" +
	"\x11CancelReservation\x12$.booking.v1.CancelReservationRequest\x1a%.booking.v1.CancelReservationResponse\x12c\n" +
	"\x12ConfirmReservation\x12%.booking.v1.ConfirmReservationRequest\x1a&.booking.v1.ConfirmReservationResponseB;Z9github.com/FrederickAlmeida/Reserva-Salas/proto;bookingpbb\x06proto3"

var (
	file_proto_reservation_proto_rawDescOnce sync.Once
	file_proto_reservation_proto_rawDescData []byte
)

func file_proto_reservation_proto_rawDescGZIP() []byte {
	file_proto_reservation_proto_rawDescOnce.Do(func() {
		file_proto_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reservation_proto_rawDesc), len(file_proto_reservation_proto_rawDesc)))
	})
	return file_proto_reservation_proto_rawDescData
}

var file_proto_reservation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_reservation_proto_goTypes = []any{
	(ReservationStatus)(0),             // 0: booking.v1.ReservationStatus
	(*TimeSlot)(nil),                   // 1: booking.v1.TimeSlot
	(*Reservation)(nil),                // 2: booking.v1.Reservation
	(*ListAvailableRequest)(nil),       // 3: booking.v1.ListAvailableRequest
	(*RoomAvailability)(nil),           // 4: booking.v1.RoomAvailability
	(*ListAvailableResponse)(nil),      // 5: booking.v1.ListAvailableResponse
	(*CreateReservationRequest)(nil),   // 6: booking.v1.CreateReservationRequest
	(*CreateReservationResponse)(nil),  // 7: booking.v1.CreateReservationResponse
	(*CancelReservationRequest)(nil),   // 8: booking.v1.CancelReservationRequest
	(*CancelReservationResponse)(nil),  // 9: booking.v1.CancelReservationResponse
	(*ConfirmReservationRequest)(nil),  // 10: booking.v1.ConfirmReservationRequest
	(*ConfirmReservationResponse)(nil), // 11: booking.v1.ConfirmReservationResponse
}
var file_proto_reservation_proto_depIdxs = []int32{
	0,  // 0: booking.v1.Reservation.status:type_name -> booking.v1.ReservationStatus
	1,  // 1: booking.v1.RoomAvailability.free_slots:type_name -> booking.v1.TimeSlot
	4,  // 2: booking.v1.ListAvailableResponse.rooms:type_name -> booking.v1.RoomAvailability
	0,  // 3: booking.v1.CreateReservationResponse.status:type_name -> booking.v1.ReservationStatus
	0,  // 4: booking.v1.CancelReservationResponse.status:type_name -> booking.v1.ReservationStatus
	0,  // 5: booking.v1.ConfirmReservationResponse.status:type_name -> booking.v1.ReservationStatus
	3,  // 6: booking.v1.ReservationService.ListAvailable:input_type -> booking.v1.ListAvailableRequest
	6,  // 7: booking.v1.ReservationService.CreateReservation:input_type -> booking.v1.CreateReservationRequest
	8,  // 8: booking.v1.ReservationService.CancelReservation:input_type -> booking.v1.CancelReservationRequest
	10, // 9: booking.v1.ReservationService.ConfirmReservation:input_type -> booking.v1.ConfirmReservationRequest
	5,  // 10: booking.v1.ReservationService.ListAvailable:output_type -> booking.v1.ListAvailableResponse
	7,  // 11: booking.v1.ReservationService.CreateReservation:output_type -> booking.v1.CreateReservationResponse
	9,  // 12: booking.v1.ReservationService.CancelReservation:output_type -> booking.v1.CancelReservationResponse
	11, // 13: booking.v1.ReservationService.ConfirmReservation:output_type -> booking.v1.ConfirmReservationResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_reservation_proto_init() }
func file_proto_reservation_proto_init() {
	if File_proto_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reservation_proto_rawDesc), len(file_proto_reservation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reservation_proto_goTypes,
		DependencyIndexes: file_proto_reservation_proto_depIdxs,
		EnumInfos:         file_proto_reservation_proto_enumTypes,
		MessageInfos:      file_proto_reservation_proto_msgTypes,
	}.Build()
	File_proto_reservation_proto = out.File
	file_proto_reservation_proto_goTypes = nil
	file_proto_reservation_proto_depIdxs = nil
}
